#!/usr/bin/env python

import sys
import re

from grc import pexpect

from grc.term import TerminalController

from yaml import load

CONF = load(open('pysetup.yml'))

from pprint import pprint; pprint(CONF)

STATE = ['root']

tc = TerminalController()
child = pexpect.spawn(" ".join(sys.argv[1:]))
for line in child:
    line = line.strip()
    for rule in CONF[STATE[-1]]:
        # rule defaults
        regex = re.compile(rule.get('match', r'^.*$'))
        replace = rule.get('replace', r'\0')
        push = rule.get('push', None)
        pop = rule.get('pop', False)
        continue_ = rule.get('continue', False)

        # transform the line if necessary
        match = regex.search(line)
        if match:
            line = regex.sub(replace, line)
            if push:
                STATE.append(push)
            if pop and len(STATE) > 1:
                STATE.pop()

            if not continue_:
                break

    print tc.render(line)


